name: groundwater_monitoring
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #dropdownfield: ^1.0.3
  animated_text_kit: ^4.2.1
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4+3               #ADD THESE LINES
  firebase_auth: ^0.16.0                #ADD THESE LINES
  cloud_firestore: ^0.13.5
  intl: ^0.17.0
  google_nav_bar: ^5.0.5
  syncfusion_flutter_charts: ^19.1.64
  dropdown_search: ^0.6.1
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
